name: run checks

on: [push]

jobs:
  ci:
    name: run all checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.11]

    steps:
    - run: npm ci
    - run: make lint